//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: data.cpp
//  Source: data.idl
//  Generated: Wed Jun  8 21:43:46 2016
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "data.h"




