//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: data.h
//  Source: data.idl
//  Generated: Wed Jun  8 21:43:46 2016
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _DATA_H_
#define _DATA_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace NetworkPartitionsData
{
   struct ChatMessage;

   struct ChatMessage
   {
         DDS::Long userID;
         DDS::Long index;
         DDS::String_mgr content;
   };

   typedef DDS_DCPSStruct_var < ChatMessage> ChatMessage_var;
   typedef DDS_DCPSStruct_out < ChatMessage> ChatMessage_out;
}




#endif 
