//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: MSFPPacket.cpp
//  Source: MSFPPacket.idl
//  Generated: Mon Jun 20 15:15:22 2016
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "MSFPPacket.h"




